org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1]
neo_version=21.1.248
neo_version_range=[21.1.0,21.2)
loader_version_range=[4,)

## Mod Properties
mod_id=bsod
mod_name=Fixed the bug where there was no BSOD in Minecraft
mod_license=MIT
mod_version=1.0.0
mod_group_id=www.unsa.bsod.com
mod_authors=UNSA Studio
mod_description=We've fixed the missing BSOD in Minecraft! Now you can feast on tasty BSOD errors! XD
